# Generated by Django 5.0.1 on 2024-01-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finalizado",
            field=models.DateField(null=True),
        ),
    ]
